// <auto-generated />
using System;
using MeetupPlatform.Api.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetupPlatformApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220415151210_AddComments")]
    partial class AddComments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Comments.ReplyComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted");

                    b.Property<Guid>("RootCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_comment_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_reply_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_reply_comments_author_id");

                    b.HasIndex("RootCommentId")
                        .HasDatabaseName("ix_reply_comments_root_comment_id");

                    b.ToTable("reply_comments", (string)null);
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Comments.RootComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_root_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_root_comments_author_id");

                    b.HasIndex("MeetupId")
                        .HasDatabaseName("ix_root_comments_meetup_id");

                    b.ToTable("root_comments", (string)null);
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Meetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_meetups");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_meetups_organizer_id");

                    b.ToTable("meetups", (string)null);
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PlainUser");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("role").HasValue("User");
                });

            modelBuilder.Entity("meetups_users_signups", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("meetup_id")
                        .HasColumnType("uuid");

                    b.HasKey("user_id", "meetup_id")
                        .HasName("pk_meetups_users_signup");

                    b.HasIndex("meetup_id")
                        .HasDatabaseName("ix_meetups_users_signups_meetup_id");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_meetups_users_signups_user_id");

                    b.ToTable("meetups_users_signups");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.Organizer", b =>
                {
                    b.HasBaseType("MeetupPlatform.Api.Domain.Users.User");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.PlainUser", b =>
                {
                    b.HasBaseType("MeetupPlatform.Api.Domain.Users.User");

                    b.HasDiscriminator().HasValue("PlainUser");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Comments.ReplyComment", b =>
                {
                    b.HasOne("MeetupPlatform.Api.Domain.Users.PlainUser", null)
                        .WithMany("ReplyComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reply_comments_users_author_id");

                    b.HasOne("MeetupPlatform.Api.Domain.Comments.RootComment", null)
                        .WithMany("ReplyComments")
                        .HasForeignKey("RootCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reply_comments_root_comments_root_comment_id");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Comments.RootComment", b =>
                {
                    b.HasOne("MeetupPlatform.Api.Domain.Users.PlainUser", null)
                        .WithMany("RootComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_root_comments_users_author_id");

                    b.HasOne("MeetupPlatform.Api.Domain.Meetup", null)
                        .WithMany("RootComments")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_root_comments_meetups_meetup_id");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Meetup", b =>
                {
                    b.HasOne("MeetupPlatform.Api.Domain.Users.Organizer", null)
                        .WithMany("OrganizedMeetups")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_meetups_organizer_id");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("MeetupPlatform.Api.Domain.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_refresh_tokens_user_id");
                });

            modelBuilder.Entity("meetups_users_signups", b =>
                {
                    b.HasOne("MeetupPlatform.Api.Domain.Meetup", null)
                        .WithMany()
                        .HasForeignKey("meetup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_users_signups_meetups_meetup_id");

                    b.HasOne("MeetupPlatform.Api.Domain.Users.PlainUser", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_users_signups_plain_users_user_id");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Comments.RootComment", b =>
                {
                    b.Navigation("ReplyComments");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Meetup", b =>
                {
                    b.Navigation("RootComments");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.Organizer", b =>
                {
                    b.Navigation("OrganizedMeetups");
                });

            modelBuilder.Entity("MeetupPlatform.Api.Domain.Users.PlainUser", b =>
                {
                    b.Navigation("ReplyComments");

                    b.Navigation("RootComments");
                });
#pragma warning restore 612, 618
        }
    }
}
